In [2]:
import numpy as np

## 1. Calculating total revenue

In [2]:
prices = np.array([19.99, 29.99, 14.99, 9.99, 24.99])
prices

array([19.99, 29.99, 14.99,  9.99, 24.99])

In [4]:
quantities = np.array([10, 5, 8, 12, 3])
quantities

array([10,  5,  8, 12,  3])

In [5]:
revenue_rer_product = prices * quantities
revenue_rer_product

array([199.9 , 149.95, 119.92, 119.88,  74.97])

In [6]:
total_revenue = np.sum(revenue_rer_product)
total_revenue

664.62

## 2. Analyzing blog post stats

In [7]:
views = np.array([1000, 500, 800, 1200, 300, 600])
views

array([1000,  500,  800, 1200,  300,  600])

In [9]:
max_views = np.max(views)
max_views

1200

In [10]:
min_views = np.min(views)
min_views

300

In [11]:
average_views = np.round(np.mean(views), 2)
average_views

733.33

## 3. Splitting order into batches

In [14]:
order_ids = np.array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])
order_ids

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])

In [15]:
batches = np.split(order_ids, 4)
batches

[array([1001, 1002]),
 array([1003, 1004]),
 array([1005, 1006]),
 array([1007, 1008])]

In [20]:
for i, batch in enumerate(batches):
    print('Batch', i)
    print('First element in the batch', batch[0])
    print('Second element in the batch', batch[1])
    

Batch 0
First element in the batch 1001
Second element in the batch 1002
Batch 1
First element in the batch 1003
Second element in the batch 1004
Batch 2
First element in the batch 1005
Second element in the batch 1006
Batch 3
First element in the batch 1007
Second element in the batch 1008


## 4. Categorizing product rating

In [21]:
ratings = np.array([4.5, 3.2, 2.8, 5.0, 4.1, 3.9, 4.7])
ratings

array([4.5, 3.2, 2.8, 5. , 4.1, 3.9, 4.7])

In [23]:
positive_ratings = ratings[ratings >= 4.0]
positive_ratings

array([4.5, 5. , 4.1, 4.7])

In [24]:
negative_ratings = ratings[ratings < 4.0]
negative_ratings

array([3.2, 2.8, 3.9])

## 5. Calculate total and average quantities sold

In [7]:
# each column is specific product (we have 4 products)
# each row is specific order (we have 2 orders)
order_qts = np.array([[5, 3, 2, 7], [10, 6, 3, 9]])
order_qts

array([[ 5,  3,  2,  7],
       [10,  6,  3,  9]])

In [5]:
total_quatities_sold = np.sum(order_qts)
total_quatities_sold

45

In [8]:
# quantities of the sales per product
total_quatities_sold = np.sum(order_qts, axis=0)
total_quatities_sold

array([15,  9,  5, 16])

In [9]:
# quantities of the sales per order
total_products_per_order = np.sum(order_qts, axis=1)
total_products_per_order

array([17, 28])

In [12]:
# average quantities per product across all orders
average_quantities_sold = np.mean(order_qts, axis=0)
average_quantities_sold

array([7.5, 4.5, 2.5, 8. ])

## 6. Calculate average product rating and maximum rating per category

In [13]:
# each row is one product
# each product is rated in 4 categories
product_ratings = np. array([
    [4.5, 3.2, 2.5, 5.0],
    [4.3, 3.8, 1.0, 4.8],
    [2.0, 3.6, 4.7, 0.5]
])
product_ratings

array([[4.5, 3.2, 2.5, 5. ],
       [4.3, 3.8, 1. , 4.8],
       [2. , 3.6, 4.7, 0.5]])

In [19]:
# average rating in each category
average_rating_per_category = np.round(np.mean(product_ratings, axis=0), 2)
average_rating_per_category

array([3.6 , 3.53, 2.73, 3.43])

In [20]:
# average rating for each product
average_rating_per_product = np.round(np.mean(product_ratings, axis=1), 2)
average_rating_per_product

array([3.8 , 3.47, 2.7 ])

In [21]:
# maximum rating in each category
max_rating_per_category = np.max(product_ratings, axis=0)
max_rating_per_category

array([4.5, 3.8, 4.7, 5. ])

## 7. Generation of the sample stock data

In [22]:
companies = ['Google', 'Microsoft', 'Apple']
days = ['Mon 1 April', 'Tue 2 April']
price_types = ['Open', 'Close', 'High', 'Low']

In [26]:
# shape will be (3, 2, 4)
np.random.seed(1)
stock_prices = np.round(np.random.random((len(companies), len(days), len(price_types))), 3)
stock_prices

array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [32]:
for index_axis_0, company in enumerate(companies):
    print(f'Stock prices for the {company}:')
    for index_axis_1, day in enumerate(days):
        print(f'Day: {day}')
        for index_axis_2, price in enumerate(price_types):
            print(f'{price} Price: {stock_prices[index_axis_0, index_axis_1, index_axis_2]}')
        print()
    print()

Stock prices for the Google:
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.72
High Price: 0.0
Low Price: 0.302

Day: Tue 2 April
Open Price: 0.147
Close Price: 0.092
High Price: 0.186
Low Price: 0.346


Stock prices for the Microsoft:
Day: Mon 1 April
Open Price: 0.397
Close Price: 0.539
High Price: 0.419
Low Price: 0.685

Day: Tue 2 April
Open Price: 0.204
Close Price: 0.878
High Price: 0.027
Low Price: 0.67


Stock prices for the Apple:
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.559
High Price: 0.14
Low Price: 0.198

Day: Tue 2 April
Open Price: 0.801
Close Price: 0.968
High Price: 0.313
Low Price: 0.692


